/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Grafo;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author vyckh
 */
public class Bienvenida extends javax.swing.JFrame {
    static Grafo grafo;
    /**
     * Creates new form Bienvenida
     */
    public Bienvenida(Grafo g) {
        this.grafo = g;
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
//        j.add(jp);
        
    }
    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        empezar1 = new javax.swing.JButton();
        empezar2 = new javax.swing.JButton();
        empezar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        empezar1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        empezar1.setForeground(new java.awt.Color(0, 102, 102));
        empezar1.setText("NUEVA PARTIDA");
        empezar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar1ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 280, 50));

        empezar2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        empezar2.setForeground(new java.awt.Color(0, 102, 102));
        empezar2.setText("SALIR");
        empezar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar2ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 230, 50));

        empezar3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        empezar3.setForeground(new java.awt.Color(0, 102, 102));
        empezar3.setText("COMO JUGAR");
        empezar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar3ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 230, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empezar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar1ActionPerformed
        // TODO add your handling code here:
        NuevaPartida n = new NuevaPartida(grafo);
        this.dispose();
    }//GEN-LAST:event_empezar1ActionPerformed

    private void empezar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar2ActionPerformed

    private void empezar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar3ActionPerformed
        // TODO add your handling code here:
        ComoJugar c = new ComoJugar(grafo);
        this.dispose();
    }//GEN-LAST:event_empezar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empezar1;
    private javax.swing.JButton empezar2;
    private javax.swing.JButton empezar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
