/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Busquedas.BFS;
import Busquedas.DFS;
import EDD.Grafo;
import EDD.Lista;
/**
 *
 * @author sofia
 */
public class Juego extends javax.swing.JFrame {
static Grafo grafo;
static int modo;
private Lista<String> diccionario;
    /**
     * Creates new form Bienvenida
     */
    public Juego(Grafo g, int modo) {
        this.grafo = g;
        this.modo = modo;
       
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        if(modo == 2){
            this.mode.setText("BFS");
        }
        
       if (modo == 2) { // Asegúrate de que esto esté dentro de un bloque donde solo se muestra el tablero
    this.A1.setText(String.valueOf(grafo.getVertices()[0].getLetra()));
    this.A2.setText(String.valueOf(grafo.getVertices()[1].getLetra()));
    this.A3.setText(String.valueOf(grafo.getVertices()[2].getLetra()));
    this.A4.setText(String.valueOf(grafo.getVertices()[3].getLetra()));
    this.A5.setText(String.valueOf(grafo.getVertices()[4].getLetra()));
    this.A6.setText(String.valueOf(grafo.getVertices()[5].getLetra()));
    this.A7.setText(String.valueOf(grafo.getVertices()[6].getLetra()));
    this.A8.setText(String.valueOf(grafo.getVertices()[7].getLetra()));
    this.A9.setText(String.valueOf(grafo.getVertices()[8].getLetra()));
    this.A10.setText(String.valueOf(grafo.getVertices()[9].getLetra()));
    this.A11.setText(String.valueOf(grafo.getVertices()[10].getLetra()));
    this.A12.setText(String.valueOf(grafo.getVertices()[11].getLetra()));
    this.A13.setText(String.valueOf(grafo.getVertices()[12].getLetra()));
    this.A14.setText(String.valueOf(grafo.getVertices()[13].getLetra()));
    this.A15.setText(String.valueOf(grafo.getVertices()[14].getLetra()));
    this.A16.setText(String.valueOf(grafo.getVertices()[15].getLetra()));
}

//        j.add(jp);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mode = new javax.swing.JLabel();
        empezar3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        A11 = new javax.swing.JButton();
        A12 = new javax.swing.JButton();
        A13 = new javax.swing.JButton();
        A14 = new javax.swing.JButton();
        A15 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tiempo = new javax.swing.JLabel();
        empezar2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tiempo1 = new javax.swing.JLabel();
        A16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mode.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        mode.setForeground(new java.awt.Color(255, 255, 255));
        mode.setText("DFS");
        jPanel1.add(mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        empezar3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar3.setForeground(new java.awt.Color(0, 102, 102));
        empezar3.setText("EMPEZAR");
        empezar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar3ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 210, 50));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Palabras encontradas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        A1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A1.setForeground(new java.awt.Color(0, 102, 102));
        A1.setText("A");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        jPanel1.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, 80));

        A2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A2.setForeground(new java.awt.Color(0, 102, 102));
        A2.setText("A");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        jPanel1.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 90, 80));

        A3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A3.setForeground(new java.awt.Color(0, 102, 102));
        A3.setText("A");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        jPanel1.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, 80));

        A4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A4.setForeground(new java.awt.Color(0, 102, 102));
        A4.setText("A");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        jPanel1.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 90, 80));

        A5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A5.setForeground(new java.awt.Color(0, 102, 102));
        A5.setText("A");
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        jPanel1.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, 80));

        A6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A6.setForeground(new java.awt.Color(0, 102, 102));
        A6.setText("A");
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        jPanel1.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 90, 80));

        A7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A7.setForeground(new java.awt.Color(0, 102, 102));
        A7.setText("A");
        A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7ActionPerformed(evt);
            }
        });
        jPanel1.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 90, 80));

        A8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A8.setForeground(new java.awt.Color(0, 102, 102));
        A8.setText("A");
        A8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A8ActionPerformed(evt);
            }
        });
        jPanel1.add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 90, 80));

        A9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A9.setForeground(new java.awt.Color(0, 102, 102));
        A9.setText("A");
        A9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A9ActionPerformed(evt);
            }
        });
        jPanel1.add(A9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 90, 80));

        A10.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A10.setForeground(new java.awt.Color(0, 102, 102));
        A10.setText("A");
        A10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A10ActionPerformed(evt);
            }
        });
        jPanel1.add(A10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 90, 80));

        A11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A11.setForeground(new java.awt.Color(0, 102, 102));
        A11.setText("A");
        A11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A11ActionPerformed(evt);
            }
        });
        jPanel1.add(A11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 90, 80));

        A12.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A12.setForeground(new java.awt.Color(0, 102, 102));
        A12.setText("A");
        A12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A12ActionPerformed(evt);
            }
        });
        jPanel1.add(A12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 90, 80));

        A13.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A13.setForeground(new java.awt.Color(0, 102, 102));
        A13.setText("A");
        A13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A13ActionPerformed(evt);
            }
        });
        jPanel1.add(A13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 90, 80));

        A14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A14.setForeground(new java.awt.Color(0, 102, 102));
        A14.setText("A");
        A14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A14ActionPerformed(evt);
            }
        });
        jPanel1.add(A14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 90, 80));

        A15.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A15.setForeground(new java.awt.Color(0, 102, 102));
        A15.setText("A");
        A15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A15ActionPerformed(evt);
            }
        });
        jPanel1.add(A15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 90, 80));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 310));

        tiempo.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        tiempo.setForeground(new java.awt.Color(255, 255, 255));
        tiempo.setText("0");
        jPanel1.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        empezar2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        empezar2.setForeground(new java.awt.Color(0, 102, 102));
        empezar2.setText("X");
        empezar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar2ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 60, 50));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MODO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        tiempo1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        tiempo1.setForeground(new java.awt.Color(255, 255, 255));
        tiempo1.setText("ms");
        jPanel1.add(tiempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        A16.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        A16.setForeground(new java.awt.Color(0, 102, 102));
        A16.setText("A");
        A16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A16ActionPerformed(evt);
            }
        });
        jPanel1.add(A16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 90, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empezar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar3ActionPerformed
        // TODO add your handling code here:
        long inicio = System.currentTimeMillis();
        //funcion de DFS 
        if(modo == 1){
            DFS d = new DFS(grafo);
            for (int i = 0; i < grafo.listaPalabras.length; i++) {
                this.jTextArea1.setText(this.jTextArea1.getText()+ d.busqueda(grafo.listaPalabras[i]));
            }
        }
        //funcion de BFS
        else{
            BFS d = new BFS(grafo);
            for (int i = 0; i < grafo.listaPalabras.length; i++) {
                this.jTextArea1.setText(this.jTextArea1.getText()+ d.busqueda(grafo.listaPalabras[i]));
            }
        }
        
        long fin = System.currentTimeMillis();
        long total = fin - inicio;
        this.tiempo.setText(String.valueOf(total));
    }//GEN-LAST:event_empezar3ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A6ActionPerformed

    private void A7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A7ActionPerformed

    private void A8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A8ActionPerformed

    private void A9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A9ActionPerformed

    private void A10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A10ActionPerformed

    private void A11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A11ActionPerformed

    private void A12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A12ActionPerformed

    private void A13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A13ActionPerformed

    private void A14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A14ActionPerformed

    private void A15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A15ActionPerformed

    private void empezar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar2ActionPerformed
        // TODO add your handling code here:
        Bienvenida m = new Bienvenida(grafo);
        this.dispose();
    }//GEN-LAST:event_empezar2ActionPerformed

    private void A16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego(grafo, modo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A10;
    private javax.swing.JButton A11;
    private javax.swing.JButton A12;
    private javax.swing.JButton A13;
    private javax.swing.JButton A14;
    private javax.swing.JButton A15;
    private javax.swing.JButton A16;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JButton empezar2;
    private javax.swing.JButton empezar3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel mode;
    private javax.swing.JLabel tiempo;
    private javax.swing.JLabel tiempo1;
    // End of variables declaration//GEN-END:variables
}
