/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Grafo;

/**
 *
 * @author sofia
 */
public class Juego extends javax.swing.JFrame {
static Grafo grafo;
static int modo;
    /**
     * Creates new form Bienvenida
     */
    public Juego(Grafo g, int modo) {
        this.grafo = g;
        this.modo = modo;
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        if(modo == 2){
            this.mode.setText("BFS");
        }
//        j.add(jp);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mode = new javax.swing.JLabel();
        empezar3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        empezar4 = new javax.swing.JButton();
        empezar5 = new javax.swing.JButton();
        empezar6 = new javax.swing.JButton();
        empezar7 = new javax.swing.JButton();
        empezar8 = new javax.swing.JButton();
        empezar9 = new javax.swing.JButton();
        empezar10 = new javax.swing.JButton();
        empezar11 = new javax.swing.JButton();
        empezar12 = new javax.swing.JButton();
        empezar13 = new javax.swing.JButton();
        empezar14 = new javax.swing.JButton();
        empezar15 = new javax.swing.JButton();
        empezar16 = new javax.swing.JButton();
        empezar17 = new javax.swing.JButton();
        empezar18 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tiempo = new javax.swing.JLabel();
        empezar2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tiempo1 = new javax.swing.JLabel();
        empezar19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mode.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        mode.setForeground(new java.awt.Color(255, 255, 255));
        mode.setText("DFS");
        jPanel1.add(mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        empezar3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar3.setForeground(new java.awt.Color(0, 102, 102));
        empezar3.setText("EMPEZAR");
        empezar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar3ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 210, 50));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Palabras encontradas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        empezar4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar4.setForeground(new java.awt.Color(0, 102, 102));
        empezar4.setText("A");
        empezar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar4ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, 80));

        empezar5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar5.setForeground(new java.awt.Color(0, 102, 102));
        empezar5.setText("A");
        empezar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar5ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 90, 80));

        empezar6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar6.setForeground(new java.awt.Color(0, 102, 102));
        empezar6.setText("A");
        empezar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar6ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, 80));

        empezar7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar7.setForeground(new java.awt.Color(0, 102, 102));
        empezar7.setText("A");
        empezar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar7ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 90, 80));

        empezar8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar8.setForeground(new java.awt.Color(0, 102, 102));
        empezar8.setText("A");
        empezar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar8ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, 80));

        empezar9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar9.setForeground(new java.awt.Color(0, 102, 102));
        empezar9.setText("A");
        empezar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar9ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 90, 80));

        empezar10.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar10.setForeground(new java.awt.Color(0, 102, 102));
        empezar10.setText("A");
        empezar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar10ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 90, 80));

        empezar11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar11.setForeground(new java.awt.Color(0, 102, 102));
        empezar11.setText("A");
        empezar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar11ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 90, 80));

        empezar12.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar12.setForeground(new java.awt.Color(0, 102, 102));
        empezar12.setText("A");
        empezar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar12ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 90, 80));

        empezar13.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar13.setForeground(new java.awt.Color(0, 102, 102));
        empezar13.setText("A");
        empezar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar13ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 90, 80));

        empezar14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar14.setForeground(new java.awt.Color(0, 102, 102));
        empezar14.setText("A");
        empezar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar14ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 90, 80));

        empezar15.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar15.setForeground(new java.awt.Color(0, 102, 102));
        empezar15.setText("A");
        empezar15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar15ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 90, 80));

        empezar16.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar16.setForeground(new java.awt.Color(0, 102, 102));
        empezar16.setText("A");
        empezar16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar16ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 90, 80));

        empezar17.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar17.setForeground(new java.awt.Color(0, 102, 102));
        empezar17.setText("A");
        empezar17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar17ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 90, 80));

        empezar18.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar18.setForeground(new java.awt.Color(0, 102, 102));
        empezar18.setText("A");
        empezar18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar18ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 90, 80));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 310));

        tiempo.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        tiempo.setForeground(new java.awt.Color(255, 255, 255));
        tiempo.setText("0");
        jPanel1.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        empezar2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        empezar2.setForeground(new java.awt.Color(0, 102, 102));
        empezar2.setText("X");
        empezar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar2ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 60, 50));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MODO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        tiempo1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        tiempo1.setForeground(new java.awt.Color(255, 255, 255));
        tiempo1.setText("ms");
        jPanel1.add(tiempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        empezar19.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        empezar19.setForeground(new java.awt.Color(0, 102, 102));
        empezar19.setText("A");
        empezar19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar19ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 90, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empezar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar3ActionPerformed
        // TODO add your handling code here:
        long inicio = System.currentTimeMillis();
        //funcion de DFS 
        if(modo == 1){
            
        }
        //funcion de BFS
        else{
            
        }
        
        long fin = System.currentTimeMillis();
        long total = fin - inicio;
        this.tiempo.setText(String.valueOf(total));
    }//GEN-LAST:event_empezar3ActionPerformed

    private void empezar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar4ActionPerformed

    private void empezar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar5ActionPerformed

    private void empezar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar6ActionPerformed

    private void empezar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar7ActionPerformed

    private void empezar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar8ActionPerformed

    private void empezar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar9ActionPerformed

    private void empezar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar10ActionPerformed

    private void empezar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar11ActionPerformed

    private void empezar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar12ActionPerformed

    private void empezar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar13ActionPerformed

    private void empezar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar14ActionPerformed

    private void empezar15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar15ActionPerformed

    private void empezar16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar16ActionPerformed

    private void empezar17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar17ActionPerformed

    private void empezar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar18ActionPerformed

    private void empezar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar2ActionPerformed
        // TODO add your handling code here:
        Bienvenida m = new Bienvenida(grafo);
        this.dispose();
    }//GEN-LAST:event_empezar2ActionPerformed

    private void empezar19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empezar19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego(grafo, modo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empezar10;
    private javax.swing.JButton empezar11;
    private javax.swing.JButton empezar12;
    private javax.swing.JButton empezar13;
    private javax.swing.JButton empezar14;
    private javax.swing.JButton empezar15;
    private javax.swing.JButton empezar16;
    private javax.swing.JButton empezar17;
    private javax.swing.JButton empezar18;
    private javax.swing.JButton empezar19;
    private javax.swing.JButton empezar2;
    private javax.swing.JButton empezar3;
    private javax.swing.JButton empezar4;
    private javax.swing.JButton empezar5;
    private javax.swing.JButton empezar6;
    private javax.swing.JButton empezar7;
    private javax.swing.JButton empezar8;
    private javax.swing.JButton empezar9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel mode;
    private javax.swing.JLabel tiempo;
    private javax.swing.JLabel tiempo1;
    // End of variables declaration//GEN-END:variables
}
