/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Grafo;

/**
 *
 * @author sofia
 */
public class NuevaPartida extends javax.swing.JFrame {
static Grafo grafo;
    /**
     * Creates new form Bienvenida
     */
    public NuevaPartida(Grafo g) {
        this.grafo = g;
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.jLabel1.setVisible(false);
        if(this.grafo == null){
            this.dfs.setEnabled(false);
            this.bfs.setEnabled(false);
            this.jLabel1.setVisible(true);
        }
//        j.add(jp);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dfs = new javax.swing.JButton();
        bfs = new javax.swing.JButton();
        empezar3 = new javax.swing.JButton();
        empezar4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carga un archivo primero para comenzar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        dfs.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        dfs.setForeground(new java.awt.Color(0, 102, 102));
        dfs.setText("MODO DFS");
        dfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsActionPerformed(evt);
            }
        });
        jPanel1.add(dfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 230, 50));

        bfs.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        bfs.setForeground(new java.awt.Color(0, 102, 102));
        bfs.setText("MODO BFS");
        bfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsActionPerformed(evt);
            }
        });
        jPanel1.add(bfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 230, 50));

        empezar3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        empezar3.setForeground(new java.awt.Color(0, 102, 102));
        empezar3.setText("CARGAR ARCHIVO");
        empezar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar3ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 260, 50));

        empezar4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        empezar4.setForeground(new java.awt.Color(0, 102, 102));
        empezar4.setText("X");
        empezar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezar4ActionPerformed(evt);
            }
        });
        jPanel1.add(empezar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 60, 50));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUEVA PARTIDA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsActionPerformed
        // TODO add your handling code here:
        Juego j = new Juego(grafo, 1);
        this.dispose();
    }//GEN-LAST:event_dfsActionPerformed

    private void bfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsActionPerformed
        // TODO add your handling code here:
           Juego j = new Juego(grafo, 2);
        this.dispose();
    }//GEN-LAST:event_bfsActionPerformed

    private void empezar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar3ActionPerformed
        // TODO add your handling code here:
        Cargar c = new Cargar(grafo);
        this.dispose();
    }//GEN-LAST:event_empezar3ActionPerformed

    private void empezar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezar4ActionPerformed
        // TODO add your handling code here:
        Bienvenida m = new Bienvenida(grafo);
        this.dispose();
    }//GEN-LAST:event_empezar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaPartida(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bfs;
    private javax.swing.JButton dfs;
    private javax.swing.JButton empezar3;
    private javax.swing.JButton empezar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
