/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
/**
 *
 * @author vyckh
 */
public class VentanaInstrucciones extends javax.swing.JFrame {
    private JTextArea txtAreaInstrucciones;
    private JButton btnVolver;
    private JScrollPane jScrollPane1;
    /**
     * Creates new form VentanaInstrucciones
     */
    public VentanaInstrucciones() {
        initComponents();
         this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Cómo Jugar");
        
        txtAreaInstrucciones.setText(
            "¡Bienvenido a la Sopa de Letras!\n\n" +
            "Cómo Jugar:\n" +
            "1. En la pantalla principal, elige 'Jugar' para iniciar una nueva partida.\n" +
            "2. La siguiente ventana te permitirá cargar palabras a tu diccionario. Puedes añadir tus propias palabras (una por línea).\n" +
            "3. Luego, se te presentará el tablero de 4x4 letras.\n" +
            "4. Puedes:\n" +
            "   - Buscar una palabra específica: Escribe la palabra en el campo de texto y haz clic en 'Buscar Palabra'.\n" +
            "   - Buscar todas las palabras: Usa 'Buscar Todas (DFS)' o 'Buscar Todas (BFS)' para encontrar todas las palabras válidas en el tablero usando el diccionario actual.\n" +
            "5. ¡Importante! Si buscas una palabra específica y el juego la encuentra en el tablero, esta palabra se añadirá automáticamente a tu diccionario personal.\n" +
            "6. Las palabras se forman conectando letras adyacentes (horizontal, vertical o diagonalmente).\n" +
            "7. Una celda no puede ser usada dos veces en la misma palabra.\n" +
            "8. El botón 'Visualizar Árbol' te mostrará el árbol de búsqueda (BFS o DFS) de la última palabra específica buscada (si se encontró).\n" +
            "9. Puedes agregar nuevas palabras al diccionario en cualquier momento en la pantalla de carga del diccionario, y volver a la pantalla de juego.\n" +
            "\n¡Diviértete encontrando palabras!"
        );
        txtAreaInstrucciones.setCaretPosition(0); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 68, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jScrollPane4.setViewportView(jScrollPane3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 220, 100));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
 new VentanaPrincipal().setVisible(true); // Vuelve a la ventana principal
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInstrucciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
