/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import EDD.Grafo;
import EDD.Diccionario;
import EDD.Vertice; // Necesario para cargar el grafo

import javax.swing.JOptionPane;
import java.awt.BorderLayout; // Importa los layouts que uses
import java.awt.FlowLayout;
import java.awt.Font; // Para fuentes
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author vyckh
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    // --- Variables globales estáticas (accesibles desde otras ventanas) ---
    public static EDD.Grafo grafo;
    public static EDD.Diccionario diccionario; // Este diccionario se actualiza a lo largo del juego

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
         if (VentanaPrincipal.grafo == null) { // Para asegurar que no se inicialice varias veces
            VentanaPrincipal.grafo = new EDD.Grafo();
            cargarTableroInicial(); // Carga las letras en el grafo
        }
        if (VentanaPrincipal.diccionario == null) { // Para asegurar que no se inicialice varias veces
            VentanaPrincipal.diccionario = new EDD.Diccionario();
            cargarDiccionarioInicialHardcodeado(); // Carga el diccionario con palabras base
        }
    }
private void cargarTableroInicial() {
        char[] letrasTablero = {
            'A', 'B', 'C', 'D',
            'E', 'F', 'G', 'H',
            'I', 'J', 'K', 'L',
            'M', 'N', 'O', 'P'
        };

        int vertIndex = 0;
        for (int r = 0; r < 4; r++) {
            for (int c = 0; c < 4; c++) {
                EDD.Vertice v = new EDD.Vertice(letrasTablero[vertIndex], r, c);
                VentanaPrincipal.grafo.agregarVertice(v);
                vertIndex++;
            }
        }
        if (VentanaPrincipal.grafo.getNumVertices() == 16) {
            VentanaPrincipal.grafo.establecerAdyacencias();
        } else {
            JOptionPane.showMessageDialog(this, "Error interno al inicializar el tablero.", "Error Grave", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarDiccionarioInicialHardcodeado() {
        String[] palabrasIniciales = {
            "CASA", "PERRO", "GATO", "SOL", "LUNA", "ARBOL", "PAZ", "AMOR",
            "DIA", "NOCHE", "ROJO", "VERDE", "AZUL", "RIO", "MAR", "HOLA", "ADIOS"
        };

        for (String palabra : palabrasIniciales) {
            VentanaPrincipal.diccionario.agregar(palabra);
        }
    }
    
    
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        Comojugar = new javax.swing.JButton();
        Jugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 40, 40));

        Comojugar.setText("Como jugar?");
        Comojugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComojugarActionPerformed(evt);
            }
        });
        jPanel1.add(Comojugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        Jugar.setText("Jugar");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        jPanel1.add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void ComojugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComojugarActionPerformed
        new VentanaInstrucciones().setVisible(true);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_ComojugarActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
    new VentanaCargaDiccionario().setVisible(true);
            this.dispose(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_JugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) { // O "Windows", "Metal", etc.
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Ejecuta la interfaz gráfica en el Event Dispatch Thread (EDT)
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comojugar;
    private javax.swing.JButton Jugar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
