/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.BuscadorPalabrasGrafo;
import EDD.Vertice;
import EDD.Grafo;
import EDD.Diccionario;
import EDD.Lista; 

import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
/**
 *
 * @author vyckh
 */
public class VentanaJuegoSopaLetras extends javax.swing.JFrame {
    private BuscadorPalabrasGrafo buscador;
    private Lista ultimoCaminoEncontrado; // Para guardar el camino de la última palabra buscada
    private String ultimaPalabraBuscadaEspecifica;
    /**
     * Creates new form VentanaJuegoSopaLetras
     */
    public VentanaJuegoSopaLetras() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Sopa de Letras - ¡A Jugar!");

        // Inicializa el buscador con el grafo global
        this.buscador = new BuscadorPalabrasGrafo(VentanaPrincipal.grafo);

        mostrarTablero(); // Rellena el tablero con las letras del grafo
        mostrarDiccionarioActual();
    }

    
     private void mostrarTablero() {
        EDD.Vertice[] verticesGrafo = VentanaPrincipal.grafo.getVertices();
        for (int r = 0; r < 4; r++) {
            for (int c = 0; c < 4; c++) {
                // Busca el vértice en la posición (r, c)
                Vertice v = null;
                for (int i = 0; i < VentanaPrincipal.grafo.getNumVertices(); i++) {
                    if (verticesGrafo[i] != null && verticesGrafo[i].getFila() == r && verticesGrafo[i].getColumna() == c) {
                        v = verticesGrafo[i];
                        break;
                    }
                }
                if (v != null) {
                    tableroLabels[r][c].setText(String.valueOf(v.getLetra()));
                } else {
                    tableroLabels[r][c].setText(""); // En caso de que no haya vértice
                }
            }
        }
    }
     
     private void mostrarDiccionarioActual() {
        StringBuilder sb = new StringBuilder("Diccionario Actual:\n");
        // Asegúrate de que el diccionario no sea null
        if (VentanaPrincipal.diccionario != null) {
            for (int i = 0; i < VentanaPrincipal.diccionario.getTamano(); i++) {
                sb.append("- ").append(VentanaPrincipal.diccionario.obtener(i)).append("\n");
            }
        } else {
            sb.append("Diccionario no disponible.");
        }
        if (txtAreaDiccionario != null) {
            txtAreaDiccionario.setText(sb.toString());
            txtAreaDiccionario.setCaretPosition(0); // Vuelve al inicio del texto
        }
    }
     
     private String trimAndToUpperCase(String s) {
        if (s == null) return "";
        s = s.trim();
        if (s.isEmpty()) return "";
        return s.toUpperCase();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuegoSopaLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuegoSopaLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuegoSopaLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuegoSopaLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuegoSopaLetras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
